import {StyleSheet} from "react-native";

export const styles = StyleSheet.create({
    containerMenu: {
        position: "relative",
        // left: "70%",
        top:0,
        float: 'left',
        marginRight: "auto",
        zIndex:500,
        height:150,
        width: '100%',
        fontSize:30,
    },
    buttonIconChat: {
        position: 'absolute',
        left: 28,
    },
    buttonIconSettings: {
        position: 'absolute',
        left: 10,
    },
    buttonIconContacts: {
        position: 'absolute',
        left: 10,
    },
    buttonIconRegistration: {
        position: 'absolute',
        left: 20,
    },
    buttonIconLogin: {
        position: 'absolute',
        left: 51,
    },
    menuContainer: {
        flex: 1,
        color: 'black',
        width: 1000,
        maxWidth: "100%",
        borderRadius:15,
        position: 'relative',
        fontSize: 20,
    },
    tabBarLabelStyle: {
        fontFamily : 'Wittgenstein-Regular',
        fontSize: 22,
        textTransform: 'none',
        left: 34,
        fontWeight: 600,
        top: -10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    tabBarLabelStyleChat: {
        fontFamily : 'Wittgenstein-Regular',
        fontSize: 22,
        textTransform: 'none',
        left: 100,
        zIndex:1,
        top: -75,
        alignItems: 'center',
        justifyContent: 'center',
    },
    tabBarLabelStyleChatStatus: {
        fontFamily : 'Wittgenstein-Regular',
        fontSize: 18,
        textTransform: 'none',
        left: 100,
        zIndex:1,
        top: -75,
        alignItems: 'center',
        justifyContent: 'center',
        color: '#fff',
    },
    tabBarLabelStyleChats: {
        fontFamily : 'Wittgenstein-Regular',
        fontSize: 30,
        top: 5
    },
    tabBarLabelStyleL: {
        fontFamily : 'Wittgenstein-Regular',
        fontSize: 22,
        textTransform: 'none',
        left: 7,
        fontWeight: 600,
        top: -2,
        alignItems: 'center',
        justifyContent: 'center',
    },
    tabBarLabelStyleR: {
        fontFamily : 'Wittgenstein-Regular',
        fontSize: 22,
        textTransform: 'none',
        right: -10,
        fontWeight: 600,
        top: -2,
        alignItems: 'center',
        justifyContent: 'center',
    },
    ChatView: {
        top: -20,
        right: -40,
        marginRight: "auto",
        float: "left",
    },
    GoBack: {
        top: 16,
        right: -5,
        marginRight: "auto",
        float: "left",
        visibility: "visible",
        justifyContent: "flex-start",
        alignItems: 'start',
    },
    containerTopChat: {
        backgroundColor: '#03fc5e',
        margin: 0,
        top: -32,
        height: 50,
        borderRadius:100,
        width:'100%',
        right: -5
    },
    containerTopChats: {
        margin: 0,
        top: -12,
        height: 50,
        width:'100%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    containerTopSettingsAndContacts: {
        backgroundColor: '#03fc5e',
        margin: 0,
        top: 0,
        height: 50,
        borderRadius:100,
        width:'100%',
        right: 1
    },
    // containerTopAvatarProfile: {
    //     backgroundColor: '#03fc5e',
    //     margin: 0,
    //     top: 0,
    //     height: 50,
    //     borderRadius:100,
    //     width:'100%',
    //     right: 4
    // },
    // containerTopProfile: {
    //     backgroundColor: '#03fc5e',
    //     margin: 0,
    //     top: 0,
    //     height: 50,
    //     borderRadius:100,
    //     width:'100%',
    //     right: 10
    // },
    GoBackSettingsAndContacts: {
        top: 16,
        left: 6,
        marginRight: "auto",
        float: "left",
        visibility: "visible",
        justifyContent: "flex-start",
        alignItems: 'start',
    },
});