---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-secret
  labels:
    app: zookeeper
  namespace: confluent
  annotations:
    job-date: "${JOB_DATE}"
data:
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_TICK_TIME: "2000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-secret
  labels:
    app: kafka
  namespace: confluent
  annotations:
    job-date: "${JOB_DATE}"
data:
  CONFLUENT_SUPPORT_CUSTOMER_ID: "anonymous"
  KAFKA_LISTENERS: "INTERNAL://:29092,LISTENER_EXTERNAL://:9092"
  KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,LISTENER_EXTERNAL://kafka.confluent:9092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_BROKER_ID: "1"
  KAFKA_DEFAULT_REPLICATION_FACTOR: "1"
  KAFKA_NUM_PARTITIONS: "1"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_LOG_CLEANUP_POLICY: "compact"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  GROUP_ID: "chat-group-id"
  KAFKA_CREATE_TOPICS: "mongo_chats"
  KAFKA_SOCKET_REQUEST_MAX_BYTES: "20971520"
  KAFKA_MAX_REQUEST_SIZE: "209715200" 
  KAFKA_PRODUCER_MAX_REQUEST_SIZE: "209715200" 
  CONNECT_PRODUCER_MAX_REQUEST_SIZE: "209715200"
  KAFKA_MESSAGE_MAX_BYTES: "209715200"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-proxy-secret
  labels:
    app: rest-proxy
  namespace: confluent
  annotations:
    job-date: "${JOB_DATE}"
data:
  KAFKA_REST_HOST_NAME: "rest-proxy"
  KAFKA_REST_BOOTSTRAP_SERVERS: "kafka:29092"
  KAFKA_REST_LISTENERS: "http://0.0.0.0:8085"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: connect-secret
  labels:
    app: connect
  namespace: confluent
  annotations:
    job-date: "${JOB_DATE}"
data:
  BOOTSTRAP_SERVERS: "kafka:29092"
  GROUP_ID: "1"
  CONFIG_STORAGE_TOPIC: "connect_configs"
  OFFSET_STORAGE_TOPIC: "connect_offsets"
  STATUS_STORAGE_TOPIC: "connect_statuses"
  CONFIG_STORAGE_REPLICATION_FACTOR: "1"
  OFFSET_STORAGE_REPLICATION_FACTOR: "1"
  STATUS_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
  CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
  CONNECT_MAX_REQUEST_SIZE: "209715200"
  KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  ENABLE_DEBEZIUM_SCRIPTING: "true"
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-registry-secret
  labels:
    app: schema-registry
  namespace: confluent
  annotations:
    job-date: "${JOB_DATE}"
data:
  SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka:29092"
  SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:30082"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ksqldb-server-secret
  labels:
    app: ksqldb-server
  namespace: confluent
  annotations:
    job-date: "${JOB_DATE}"
data:
  KSQL_CONFIG_DIR: "/etc/ksqldb"
  KSQL_LISTENERS: "http://localhost:8088"
  KSQL_BOOTSTRAP_SERVERS: "kafka:29092"
  KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
  KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
  KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:30082"
  KSQL_HOST_NAME: ksqldb-server
  KSQL_CONNECT_URL: "http://connect:8083"
---  
apiVersion: v1
kind: ConfigMap
metadata:
  name: debezium-ui-secret
  labels:
    app: debezium-ui
  namespace: confluent
  annotations:
    job-date: "${JOB_DATE}"
data:
  KAFKA_CONNECT_URIS: http://connect:8083
---  
  
  
  
  
 
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
