---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: backend
spec:
  ports:
    - port: 8096
      name: http
      nodePort: 30096
    - port: 4050
      name: grpc
      nodePort: 30050
  type: NodePort
  selector:
    app: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: backend
  annotations:
    job-date: "${JOB_DATE}"
spec:
  replicas: 1
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - server
  template:
    metadata:
      labels:
        app: server
      annotations:
        job-date: "${JOB_DATE}"
    spec:
      volumes:
        - name: log
          persistentVolumeClaim:
            claimName: server-pvc-log
      containers:
        - name: server
          image: myv111/server
          envFrom:
            - configMapRef:
                name: server-secret
          ports:
            - name: http
              containerPort: 8096
            - name: grpc
              containerPort: 4050
          command: ["/app/main"]    
          livenessProbe:
            tcpSocket:
              port: 8096
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 8096
            initialDelaySeconds: 5
            periodSeconds: 20
          volumeMounts:
            - name: log
              mountPath: "/app/log/logs"
              subPath: logs
---
