import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
    //     flex: 1,
    //     position: 'absolute',
    //     backgroundColor:'white',
    //     fontFamily : 'RightLato',
    //     borderTopColor: "#edf2ee",
    //     borderTopWidth: 1,
        width: "100%",
        zIndex:9999,
        height:'100%',
    //     top: -100
    },

    leftChatText: {
        width: "90%",
        left: 15,
        zIndex:9999,
        // top: 0,
        // position: 'relative',
        // padding: 5,
        // top: 15,
        height:80,
    },
    buttonIcon: {
        borderRadius: 50,
        border: 1,
        borderColor: 'red',
        position:'absolute',
        width:40,
        heigt: 40,
        zIndex:9999,
    },
    rightText: {
        left: 80,
        top:-55,
        zIndex:9999,
    },
    dateRight: {
        position:'absolute',
        right: 70,
        top: 7,
        fontSize: 14,
        zIndex:9999,
    },
    dateRightText: {
        fontSize: 14,
        fontFamily: 'DimkinBold',
        zIndex:9999,
    },
    buttonTextRight: {
        fontFamily : 'RightLato',
        fontSize: 11,
        zIndex:9999,
    },
    buttonTextRightDate: {
        fontFamily : 'RightLato',
        fontSize: 11,
        zIndex:9999,
    },
    buttonText: {
        fontFamily : 'MathItalic',
        fontSize:16,
        top: 1,
        right:20,
        zIndex:9999,
    },
    buttonTextView: {
        top: 10,
        zIndex:9999,
    },
    buttonNameText: {
        fontSize: 16,
        fontFamily: 'Wittgenstein-Italic-Regular',
        right:20,
        top: 2,
        zIndex:9999,
    },
    scrollView: {
        marginHorizontal: 20,
        //   width:280,
        //   height: 253,
        marginRight: 0,
        backgroundColor: 'green',
        zIndex:9999,
    },
    tabBarLabelStyle: {
        fontFamily : 'RightLato',
        fontSize: 22,
        textTransform: 'none',
        left: 40,
        fontWeight: 600,
        top: 9,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex:9999,
    },
    buttonIconChat: {
        position: 'absolute',
        left: 10,
        top: 18,
        zIndex:9999,
    },
    dateRightNotReadMessageView: {
        position:'absolute',
        right: 70,
        top: 7,
        fontSize: 14,
        zIndex:9999,
    },
    countNotReadMessageView: {
        width: 25,
        height: 25,
        backgroundColor: '#15ab0a',
        top: 6,
        right: 3,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 15,
    },
    countNotReadMessageText: {
        color: '#fff',
        fontSize: 15,
    },
    viewButton: {
        backgroundColor:  "#03fc5e",
        maxWidth: "100%",
        height: 50,
        margin:5,
        borderRadius:100,
        visibility: "visible",
        justifyContent: "flex-start",
        alignItems: 'start',
    },
});