---
apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    name: minio
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-secret
  labels:
    app: minio
  namespace: minio
data:
  MINIO_ROOT_USER: ROOTNAME
  MINIO_ROOT_PASSWORD: CHANGEME123
