---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: minio
  name: minio
  namespace: minio
spec:
  ports:
    - port: 9000
      name: http
      nodePort: 30200
    - port: 9001
      name: cli
      nodePort: 30201
  type: NodePort
  selector:
    app: minio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  replicas: 1
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          securityContext:
            allowPrivilegeEscalation: true
            runAsUser: 1000
          envFrom:
            - configMapRef:
                name: minio-secret
          volumeMounts:
            - name: minio-data
              mountPath: /data
          ports:
            - name: http
              containerPort: 9000
            - name: cli
              containerPort: 9001		 	
          command:
            - /bin/bash
            - -c
          args: 
            - minio server /data --console-address :9001
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc
---          






























          
          
              
